import { and, asc, eq, gt, sql } from 'drizzle-orm';
import { db } from '../db/client.js';
import {
  paymentAllocations,
  payments,
  vHouseholdYearObligation,
  type payments as PaymentsTable,
} from '../db/schema/index.js';
import { assertCanWrite, tenantWhere, type DbOrTx, type TenantScope } from '../db/tenancy.js';
import { writeAudit } from '../lib/audit.js';
import {
  allocateFifo,
  assertAllocationsValid,
  type Allocation,
  type OutstandingYear,
} from '../lib/ledger.js';
import * as batchesRepo from '../repositories/batches.js';
import * as householdsRepo from '../repositories/households.js';
import { badRequest } from '../http/errors.js';

export type Payment = typeof PaymentsTable.$inferSelect;

/**
 * Recording a payment (SPEC §5.5).
 *
 * One transaction inserts the payment, its allocations, updates the batch total
 * and writes the audit row — all four or none (SPEC §3.1 rule 3).
 */

/**
 * Years this household still owes for, oldest first, straight from the view.
 * Never recomputed here (SPEC §5.3).
 */
export async function outstandingYears(
  tx: DbOrTx,
  scope: TenantScope,
  householdId: string,
): Promise<OutstandingYear[]> {
  const rows = await tx
    .select({
      year: vHouseholdYearObligation.year,
      balanceCents: vHouseholdYearObligation.balanceCents,
    })
    .from(vHouseholdYearObligation)
    .where(
      and(
        tenantWhere(vHouseholdYearObligation, scope),
        eq(vHouseholdYearObligation.householdId, householdId),
        gt(vHouseholdYearObligation.balanceCents, 0),
      ),
    )
    .orderBy(asc(vHouseholdYearObligation.year));

  return rows.map((row) => ({ year: row.year, balanceCents: row.balanceCents }));
}

/**
 * The allocation the UI shows before saving. It is a proposal: the collector
 * can override it, because he sometimes knows "this €50 is for 2025
 * specifically" (SPEC §5.5).
 */
export async function previewAllocation(
  scope: TenantScope,
  householdId: string,
  amountCents: number,
): Promise<{ allocations: Allocation[]; unallocatedCents: number; outstanding: OutstandingYear[] }> {
  await householdsRepo.getById(scope, householdId);
  const outstanding = await outstandingYears(db, scope, householdId);
  const { allocations, unallocatedCents } = allocateFifo(amountCents, outstanding);
  return { allocations, unallocatedCents, outstanding };
}

export interface RecordPaymentInput {
  householdId: string;
  totalCents: number;
  /** `YYYY-MM-DD`. Decides which monthly batch the payment lands in. */
  paidAt: string;
  receiptNumber: string;
  /** Generated by the client, before the payment ever reaches the server. */
  clientUuid: string;
  note?: string | null | undefined;
  /** Omit for FIFO; supply to override it. */
  allocations?: Allocation[] | undefined;
}

export interface RecordPaymentResult {
  payment: Payment;
  allocations: Allocation[];
  batchId: string;
  /**
   * True when this exact payment was already recorded. The sync replayed; the
   * ledger did not move (SPEC §9).
   */
  replayed: boolean;
  /**
   * Receipt numbers come from the paper book and are typed by hand, so
   * duplicates are surfaced rather than blocked (SPEC §9).
   */
  duplicateReceipt: boolean;
}

const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

export async function recordPayment(
  scope: TenantScope,
  input: RecordPaymentInput,
): Promise<RecordPaymentResult> {
  assertCanWrite(scope);

  if (!DATE_PATTERN.test(input.paidAt)) {
    throw badRequest('Payment date must be in YYYY-MM-DD form');
  }
  if (!Number.isSafeInteger(input.totalCents) || input.totalCents <= 0) {
    throw badRequest('Payment must be a positive whole number of cents');
  }
  if (input.receiptNumber.trim() === '') {
    throw badRequest('Receipt number is required — it matches the paper receipt');
  }

  const [yearPart, monthPart] = input.paidAt.split('-');
  const periodYear = Number(yearPart);
  const periodMonth = Number(monthPart);

  return db.transaction(async (tx) => {
    // Replay check first: a repeated sync must not even look like work.
    const [existing] = await tx
      .select()
      .from(payments)
      .where(tenantWhere(payments, scope, eq(payments.clientUuid, input.clientUuid)))
      .limit(1);

    if (existing) {
      const rows = await tx
        .select({ year: paymentAllocations.year, amountCents: paymentAllocations.amountCents })
        .from(paymentAllocations)
        .where(eq(paymentAllocations.paymentId, existing.id))
        .orderBy(asc(paymentAllocations.year));
      return {
        payment: existing,
        allocations: rows,
        batchId: existing.batchId ?? '',
        replayed: true,
        duplicateReceipt: false,
      };
    }

    await householdsRepo.getById(scope, input.householdId);

    const outstanding = await outstandingYears(tx, scope, input.householdId);
    const allocations = input.allocations ?? allocateFifo(input.totalCents, outstanding).allocations;

    assertAllocationsValid(input.totalCents, allocations);
    assertAllocationsFitWhatIsOwed(allocations, outstanding);

    const batch = await batchesRepo.findOrCreateOpenBatch(tx, scope, periodYear, periodMonth);

    const duplicateReceipt = await hasReceiptNumber(tx, scope, input.receiptNumber);

    const [payment] = await tx
      .insert(payments)
      .values({
        mosqueId: scope.mosqueId,
        householdId: input.householdId,
        batchId: batch.id,
        clientUuid: input.clientUuid,
        paidAt: input.paidAt,
        totalCents: input.totalCents,
        receiptNumber: input.receiptNumber.trim(),
        collectedBy: scope.actor.userId,
        note: input.note ?? null,
      })
      .returning();
    if (!payment) throw new Error('Insert returned no payment');

    await tx.insert(paymentAllocations).values(
      allocations.map((allocation) => ({
        mosqueId: scope.mosqueId,
        paymentId: payment.id,
        year: allocation.year,
        amountCents: allocation.amountCents,
      })),
    );

    await batchesRepo.addToGross(tx, scope, batch.id, input.totalCents);

    await writeAudit(tx, scope, {
      action: 'payment.created',
      entityType: 'payment',
      entityId: payment.id,
      after: { ...payment, allocations, duplicateReceipt },
    });

    return { payment, allocations, batchId: batch.id, replayed: false, duplicateReceipt };
  });
}

/**
 * Money may only be allocated to a year that actually owes it.
 *
 * There is no credit or prepayment concept in this ledger, so an allocation
 * beyond what a year owes would sit in the balance as a negative number and
 * silently cancel out real debt elsewhere.
 */
function assertAllocationsFitWhatIsOwed(
  allocations: Allocation[],
  outstanding: OutstandingYear[],
): void {
  const owedByYear = new Map(outstanding.map((year) => [year.year, year.balanceCents]));

  for (const allocation of allocations) {
    const owed = owedByYear.get(allocation.year);
    if (owed === undefined) {
      throw badRequest(
        `Nothing is owed for ${allocation.year}, so no money can be allocated to it`,
      );
    }
    if (allocation.amountCents > owed) {
      throw badRequest(
        `Allocated ${allocation.amountCents} cents to ${allocation.year}, which owes only ${owed}`,
      );
    }
  }
}

async function hasReceiptNumber(
  tx: DbOrTx,
  scope: TenantScope,
  receiptNumber: string,
): Promise<boolean> {
  const [row] = await tx
    .select({ count: sql<number>`count(*)::int` })
    .from(payments)
    .where(tenantWhere(payments, scope, eq(payments.receiptNumber, receiptNumber.trim())))
    .limit(1);
  return (row?.count ?? 0) > 0;
}

/** Payments are append-only; corrections are new records, never edits. */
export async function listByHousehold(
  scope: TenantScope,
  householdId: string,
): Promise<Payment[]> {
  await householdsRepo.getById(scope, householdId);
  return db
    .select()
    .from(payments)
    .where(tenantWhere(payments, scope, eq(payments.householdId, householdId)))
    .orderBy(asc(payments.paidAt));
}
