import { Router } from 'express';
import { z } from 'zod';
import type { PaymentDto, RecordPaymentResultDto } from '@mosque/shared';
import { requireRole, requireScope } from '../http/middleware/authenticate.js';
import { parseBody, parseParams } from '../http/validate.js';
import { previewAllocation, recordPayment } from '../services/payments.js';
import * as ratesRepo from '../repositories/rates.js';

export const paymentsRouter: Router = Router();


const staff = requireRole('super_admin', 'imam', 'collector');

const allocationSchema = z.object({
  year: z.number().int(),
  amountCents: z.number().int().positive(),
});

const recordBody = z.object({
  householdId: z.uuid(),
  totalCents: z.number().int().positive(),
  paidAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Use YYYY-MM-DD'),
  receiptNumber: z.string().trim().min(1).max(64),
  /**
   * Generated by the client before the payment leaves the device, so a
   * replayed offline sync is a no-op rather than a duplicate (SPEC §9).
   */
  clientUuid: z.uuid(),
  note: z.string().trim().max(2000).nullish(),
  /** Omit for FIFO; supply to override it (SPEC §5.5). */
  allocations: z.array(allocationSchema).min(1).optional(),
});

paymentsRouter.post('/payments', staff, async (req, res) => {
  const scope = requireScope(req);
  const input = parseBody(recordBody, req);
  const result = await recordPayment(scope, input);

  const payment: PaymentDto = {
    id: result.payment.id,
    paidAt: result.payment.paidAt,
    totalCents: result.payment.totalCents,
    receiptNumber: result.payment.receiptNumber,
    note: result.payment.note,
    batchId: result.payment.batchId,
    allocations: result.allocations,
  };

  const body: RecordPaymentResultDto = {
    payment,
    replayed: result.replayed,
    duplicateReceipt: result.duplicateReceipt,
  };
  // A replay is not a creation, so it does not report 201.
  res.status(result.replayed ? 200 : 201).json(body);
});

/** The allocation the UI shows before saving. Writes nothing. */
paymentsRouter.post('/payments/preview', staff, async (req, res) => {
  const scope = requireScope(req);
  const { householdId, totalCents } = parseBody(
    z.object({ householdId: z.uuid(), totalCents: z.number().int().positive() }),
    req,
  );
  res.json(await previewAllocation(scope, householdId, totalCents));
});

export const ratesRouter: Router = Router();


ratesRouter.get('/rates', async (req, res) => {
  const scope = requireScope(req);
  const rates = await ratesRepo.listByYear(scope);
  res.json({ rates: rates.map((rate) => ({ year: rate.year, amountCents: rate.amountCents })) });
});

/** Imam only — the collector must not move the price (SPEC §4.2). */
ratesRouter.put('/rates/:year', requireRole('super_admin', 'imam'), async (req, res) => {
  const scope = requireScope(req);
  const { year } = parseParams(z.object({ year: z.coerce.number().int() }), req);
  const { amountCents } = parseBody(z.object({ amountCents: z.number().int().positive() }), req);
  const rate = await ratesRepo.setRate(scope, year, amountCents);
  res.json({ rate: { year: rate.year, amountCents: rate.amountCents } });
});
